locs = ['st. petersburg', 'paris', 'new york', 'sydney', 'tokyo']
for loc in locs[:]:
	locs.remove(loc)
	locs.append(loc.title())
print(locs)
print(sorted(locs))
print(locs)
print(sorted(locs, reverse = True))
print(locs)
locs.reverse()
print(locs)
locs.reverse()
print(locs)
locs.sort()
print(locs)
locs.sort(reverse = True)
print(locs)